/* Generated by Yosys 0.45+106 (git sha1 982fade0d, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

module mux16x1(IN, SEL, OUT);
  input [15:0] IN;
  wire [15:0] IN;
  output OUT;
  wire OUT;
  input [3:0] SEL;
  wire [3:0] SEL;
  wire [3:0] t;
  mux_4x1 m1 (
    .in(IN[3:0]),
    .out(t[0]),
    .sel(SEL[1:0])
  );
  mux_4x1 m2 (
    .in(IN[7:4]),
    .out(t[1]),
    .sel(SEL[1:0])
  );
  mux_4x1 m3 (
    .in(IN[11:8]),
    .out(t[2]),
    .sel(SEL[1:0])
  );
  mux_4x1 m4 (
    .in(IN[15:12]),
    .out(t[3]),
    .sel(SEL[1:0])
  );
  mux_4x1 m5 (
    .in(t),
    .out(OUT),
    .sel(SEL[3:2])
  );
endmodule

module mux_4x1(in, sel, out);
  wire _0_;
  wire _1_;
  input [3:0] in;
  wire [3:0] in;
  output out;
  wire out;
  input [1:0] sel;
  wire [1:0] sel;
  MUX2_X1 _2_ (
    .A(in[2]),
    .B(in[3]),
    .S(sel[0]),
    .Z(_0_)
  );
  MUX2_X1 _3_ (
    .A(in[0]),
    .B(in[1]),
    .S(sel[0]),
    .Z(_1_)
  );
  MUX2_X1 _4_ (
    .A(_1_),
    .B(_0_),
    .S(sel[1]),
    .Z(out)
  );
endmodule
