/* Generated by Yosys 0.45+106 (git sha1 982fade0d, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

module top(IN, SHIFT, OUT);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  input [7:0] IN;
  wire [7:0] IN;
  output [7:0] OUT;
  wire [7:0] OUT;
  input [2:0] SHIFT;
  wire [2:0] SHIFT;
  wire [7:0] \m0.IN ;
  wire \m0.OUT ;
  wire [2:0] \m0.SHIFT ;
  wire [7:0] \m1.IN ;
  wire \m1.OUT ;
  wire [2:0] \m1.SHIFT ;
  wire [7:0] \m2.IN ;
  wire \m2.OUT ;
  wire [2:0] \m2.SHIFT ;
  wire [7:0] \m3.IN ;
  wire \m3.OUT ;
  wire [2:0] \m3.SHIFT ;
  wire [7:0] \m4.IN ;
  wire \m4.OUT ;
  wire [2:0] \m4.SHIFT ;
  wire [7:0] \m5.IN ;
  wire \m5.OUT ;
  wire [2:0] \m5.SHIFT ;
  wire [7:0] \m6.IN ;
  wire \m6.OUT ;
  wire [2:0] \m6.SHIFT ;
  wire [7:0] \m7.IN ;
  wire \m7.OUT ;
  wire [2:0] \m7.SHIFT ;
  MUX2_X1 _16_ (
    .A(IN[7]),
    .B(IN[0]),
    .S(SHIFT[0]),
    .Z(_00_)
  );
  MUX2_X1 _17_ (
    .A(IN[1]),
    .B(IN[2]),
    .S(SHIFT[0]),
    .Z(_01_)
  );
  MUX2_X1 _18_ (
    .A(_00_),
    .B(_01_),
    .S(SHIFT[1]),
    .Z(_02_)
  );
  MUX2_X1 _19_ (
    .A(IN[3]),
    .B(IN[4]),
    .S(SHIFT[0]),
    .Z(_03_)
  );
  MUX2_X1 _20_ (
    .A(IN[5]),
    .B(IN[6]),
    .S(SHIFT[0]),
    .Z(_04_)
  );
  MUX2_X1 _21_ (
    .A(_03_),
    .B(_04_),
    .S(SHIFT[1]),
    .Z(_05_)
  );
  MUX2_X1 _22_ (
    .A(_02_),
    .B(_05_),
    .S(SHIFT[2]),
    .Z(OUT[7])
  );
  MUX2_X1 _23_ (
    .A(IN[6]),
    .B(IN[7]),
    .S(SHIFT[0]),
    .Z(_06_)
  );
  MUX2_X1 _24_ (
    .A(IN[0]),
    .B(IN[1]),
    .S(SHIFT[0]),
    .Z(_07_)
  );
  MUX2_X1 _25_ (
    .A(_06_),
    .B(_07_),
    .S(SHIFT[1]),
    .Z(_08_)
  );
  MUX2_X1 _26_ (
    .A(IN[2]),
    .B(IN[3]),
    .S(SHIFT[0]),
    .Z(_09_)
  );
  MUX2_X1 _27_ (
    .A(IN[4]),
    .B(IN[5]),
    .S(SHIFT[0]),
    .Z(_10_)
  );
  MUX2_X1 _28_ (
    .A(_09_),
    .B(_10_),
    .S(SHIFT[1]),
    .Z(_11_)
  );
  MUX2_X1 _29_ (
    .A(_08_),
    .B(_11_),
    .S(SHIFT[2]),
    .Z(OUT[6])
  );
  MUX2_X1 _30_ (
    .A(_04_),
    .B(_00_),
    .S(SHIFT[1]),
    .Z(_12_)
  );
  MUX2_X1 _31_ (
    .A(_01_),
    .B(_03_),
    .S(SHIFT[1]),
    .Z(_13_)
  );
  MUX2_X1 _32_ (
    .A(_12_),
    .B(_13_),
    .S(SHIFT[2]),
    .Z(OUT[5])
  );
  MUX2_X1 _33_ (
    .A(_10_),
    .B(_06_),
    .S(SHIFT[1]),
    .Z(_14_)
  );
  MUX2_X1 _34_ (
    .A(_07_),
    .B(_09_),
    .S(SHIFT[1]),
    .Z(_15_)
  );
  MUX2_X1 _35_ (
    .A(_14_),
    .B(_15_),
    .S(SHIFT[2]),
    .Z(OUT[4])
  );
  MUX2_X1 _36_ (
    .A(_05_),
    .B(_02_),
    .S(SHIFT[2]),
    .Z(OUT[3])
  );
  MUX2_X1 _37_ (
    .A(_11_),
    .B(_08_),
    .S(SHIFT[2]),
    .Z(OUT[2])
  );
  MUX2_X1 _38_ (
    .A(_13_),
    .B(_12_),
    .S(SHIFT[2]),
    .Z(OUT[1])
  );
  MUX2_X1 _39_ (
    .A(_15_),
    .B(_14_),
    .S(SHIFT[2]),
    .Z(OUT[0])
  );
  assign \m0.IN  = IN;
  assign \m0.OUT  = OUT[0];
  assign \m0.SHIFT  = SHIFT;
  assign \m1.IN  = { IN[0], IN[7:1] };
  assign \m1.OUT  = OUT[1];
  assign \m1.SHIFT  = SHIFT;
  assign \m2.IN  = { IN[1:0], IN[7:2] };
  assign \m2.OUT  = OUT[2];
  assign \m2.SHIFT  = SHIFT;
  assign \m3.IN  = { IN[2:0], IN[7:3] };
  assign \m3.OUT  = OUT[3];
  assign \m3.SHIFT  = SHIFT;
  assign \m4.IN  = { IN[3:0], IN[7:4] };
  assign \m4.OUT  = OUT[4];
  assign \m4.SHIFT  = SHIFT;
  assign \m5.IN  = { IN[4:0], IN[7:5] };
  assign \m5.OUT  = OUT[5];
  assign \m5.SHIFT  = SHIFT;
  assign \m6.IN  = { IN[5:0], IN[7:6] };
  assign \m6.OUT  = OUT[6];
  assign \m6.SHIFT  = SHIFT;
  assign \m7.IN  = { IN[6:0], IN[7] };
  assign \m7.OUT  = OUT[7];
  assign \m7.SHIFT  = SHIFT;
endmodule
