/* Generated by Yosys 0.45+106 (git sha1 982fade0d, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

module mux8x1(IN, SHIFT, OUT);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  input [7:0] IN;
  wire [7:0] IN;
  output OUT;
  wire OUT;
  input [2:0] SHIFT;
  wire [2:0] SHIFT;
  MUX2_X1 _06_ (
    .A(IN[3]),
    .B(IN[7]),
    .S(SHIFT[2]),
    .Z(_00_)
  );
  MUX2_X1 _07_ (
    .A(IN[2]),
    .B(IN[6]),
    .S(SHIFT[2]),
    .Z(_01_)
  );
  MUX2_X1 _08_ (
    .A(_01_),
    .B(_00_),
    .S(SHIFT[0]),
    .Z(_02_)
  );
  MUX2_X1 _09_ (
    .A(IN[1]),
    .B(IN[5]),
    .S(SHIFT[2]),
    .Z(_03_)
  );
  MUX2_X1 _10_ (
    .A(IN[0]),
    .B(IN[4]),
    .S(SHIFT[2]),
    .Z(_04_)
  );
  MUX2_X1 _11_ (
    .A(_04_),
    .B(_03_),
    .S(SHIFT[0]),
    .Z(_05_)
  );
  MUX2_X1 _12_ (
    .A(_05_),
    .B(_02_),
    .S(SHIFT[1]),
    .Z(OUT)
  );
endmodule
