/* Generated by Yosys 0.45+106 (git sha1 982fade0d, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

module level_sensitive_latch(d, q, enb);
  input d;
  wire d;
  input enb;
  wire enb;
  output q;
  wire q;
  BUF_X1 _0_ (
    .A(q),
    .Z(q)
  );
endmodule
