/* Generated by Yosys 0.45+106 (git sha1 982fade0d, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

module counter_up_down(din, clr, ld, clk, mode, count);
  wire [7:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  input clk;
  wire clk;
  input clr;
  wire clr;
  output [7:0] count;
  wire [7:0] count;
  input [7:0] din;
  wire [7:0] din;
  input ld;
  wire ld;
  input mode;
  wire mode;
  INV_X1 _052_ (
    .A(count[2]),
    .ZN(_001_)
  );
  INV_X1 _053_ (
    .A(mode),
    .ZN(_002_)
  );
  NAND2_X1 _054_ (
    .A1(din[6]),
    .A2(ld),
    .ZN(_003_)
  );
  NAND3_X1 _055_ (
    .A1(count[1]),
    .A2(count[0]),
    .A3(_002_),
    .ZN(_004_)
  );
  AND4_X1 _056_ (
    .A1(count[2]),
    .A2(count[1]),
    .A3(count[0]),
    .A4(_002_),
    .ZN(_005_)
  );
  NAND2_X1 _057_ (
    .A1(count[3]),
    .A2(_005_),
    .ZN(_006_)
  );
  AND3_X1 _058_ (
    .A1(count[4]),
    .A2(count[3]),
    .A3(_005_),
    .ZN(_007_)
  );
  AND4_X1 _059_ (
    .A1(count[5]),
    .A2(count[4]),
    .A3(count[3]),
    .A4(_005_),
    .ZN(_008_)
  );
  OR2_X1 _060_ (
    .A1(count[1]),
    .A2(_002_),
    .ZN(_009_)
  );
  OR4_X1 _061_ (
    .A1(count[2]),
    .A2(count[1]),
    .A3(count[0]),
    .A4(_002_),
    .ZN(_010_)
  );
  NOR3_X1 _062_ (
    .A1(count[4]),
    .A2(count[3]),
    .A3(_010_),
    .ZN(_011_)
  );
  NOR4_X1 _063_ (
    .A1(count[5]),
    .A2(count[4]),
    .A3(count[3]),
    .A4(_010_),
    .ZN(_012_)
  );
  OR2_X1 _064_ (
    .A1(_008_),
    .A2(_012_),
    .ZN(_013_)
  );
  AND2_X1 _065_ (
    .A1(count[6]),
    .A2(_013_),
    .ZN(_014_)
  );
  NOR2_X1 _066_ (
    .A1(ld),
    .A2(clr),
    .ZN(_015_)
  );
  INV_X1 _067_ (
    .A(_015_),
    .ZN(_016_)
  );
  OAI21_X1 _068_ (
    .A(_015_),
    .B1(_013_),
    .B2(count[6]),
    .ZN(_017_)
  );
  OAI21_X1 _069_ (
    .A(_003_),
    .B1(_014_),
    .B2(_017_),
    .ZN(_000_[6])
  );
  NAND2_X1 _070_ (
    .A1(ld),
    .A2(din[5]),
    .ZN(_018_)
  );
  OAI21_X1 _071_ (
    .A(count[5]),
    .B1(_007_),
    .B2(_011_),
    .ZN(_019_)
  );
  NOR3_X1 _072_ (
    .A1(count[5]),
    .A2(_007_),
    .A3(_011_),
    .ZN(_020_)
  );
  NAND2_X1 _073_ (
    .A1(_015_),
    .A2(_019_),
    .ZN(_021_)
  );
  OAI21_X1 _074_ (
    .A(_018_),
    .B1(_020_),
    .B2(_021_),
    .ZN(_000_[5])
  );
  NAND2_X1 _075_ (
    .A1(ld),
    .A2(din[4]),
    .ZN(_022_)
  );
  OAI21_X1 _076_ (
    .A(_006_),
    .B1(_010_),
    .B2(count[3]),
    .ZN(_023_)
  );
  AND2_X1 _077_ (
    .A1(count[4]),
    .A2(_023_),
    .ZN(_024_)
  );
  OAI21_X1 _078_ (
    .A(_015_),
    .B1(_023_),
    .B2(count[4]),
    .ZN(_025_)
  );
  OAI21_X1 _079_ (
    .A(_022_),
    .B1(_024_),
    .B2(_025_),
    .ZN(_000_[4])
  );
  NAND2_X1 _080_ (
    .A1(ld),
    .A2(din[3]),
    .ZN(_026_)
  );
  OAI21_X1 _081_ (
    .A(_010_),
    .B1(_004_),
    .B2(_001_),
    .ZN(_027_)
  );
  AOI21_X1 _082_ (
    .A(_016_),
    .B1(_027_),
    .B2(count[3]),
    .ZN(_028_)
  );
  OAI21_X1 _083_ (
    .A(_028_),
    .B1(_027_),
    .B2(count[3]),
    .ZN(_029_)
  );
  NAND2_X1 _084_ (
    .A1(_026_),
    .A2(_029_),
    .ZN(_000_[3])
  );
  NAND2_X1 _085_ (
    .A1(ld),
    .A2(din[2]),
    .ZN(_030_)
  );
  OAI21_X1 _086_ (
    .A(_004_),
    .B1(_009_),
    .B2(count[0]),
    .ZN(_031_)
  );
  AOI21_X1 _087_ (
    .A(_016_),
    .B1(_031_),
    .B2(count[2]),
    .ZN(_032_)
  );
  OAI21_X1 _088_ (
    .A(_032_),
    .B1(_031_),
    .B2(count[2]),
    .ZN(_033_)
  );
  NAND2_X1 _089_ (
    .A1(_030_),
    .A2(_033_),
    .ZN(_000_[2])
  );
  XNOR2_X1 _090_ (
    .A(count[1]),
    .B(mode),
    .ZN(_034_)
  );
  NOR3_X1 _091_ (
    .A1(count[0]),
    .A2(_016_),
    .A3(_034_),
    .ZN(_035_)
  );
  NAND3_X1 _092_ (
    .A1(count[0]),
    .A2(_015_),
    .A3(_034_),
    .ZN(_036_)
  );
  AOI21_X1 _093_ (
    .A(_035_),
    .B1(din[1]),
    .B2(ld),
    .ZN(_037_)
  );
  NAND2_X1 _094_ (
    .A1(_036_),
    .A2(_037_),
    .ZN(_000_[1])
  );
  NAND2_X1 _095_ (
    .A1(ld),
    .A2(din[0]),
    .ZN(_038_)
  );
  OAI21_X1 _096_ (
    .A(_038_),
    .B1(_016_),
    .B2(count[0]),
    .ZN(_000_[0])
  );
  NAND2_X1 _097_ (
    .A1(ld),
    .A2(din[7]),
    .ZN(_039_)
  );
  XOR2_X1 _098_ (
    .A(count[6]),
    .B(mode),
    .Z(_040_)
  );
  OAI211_X1 _099_ (
    .A(count[7]),
    .B(_040_),
    .C1(_012_),
    .C2(_008_),
    .ZN(_041_)
  );
  AOI21_X1 _100_ (
    .A(count[7]),
    .B1(_013_),
    .B2(_040_),
    .ZN(_042_)
  );
  NAND2_X1 _101_ (
    .A1(_015_),
    .A2(_041_),
    .ZN(_043_)
  );
  OAI21_X1 _102_ (
    .A(_039_),
    .B1(_042_),
    .B2(_043_),
    .ZN(_000_[7])
  );
  DFF_X1 _103_ (
    .CK(clk),
    .D(_000_[0]),
    .Q(count[0]),
    .QN(_051_)
  );
  DFF_X1 _104_ (
    .CK(clk),
    .D(_000_[1]),
    .Q(count[1]),
    .QN(_050_)
  );
  DFF_X1 _105_ (
    .CK(clk),
    .D(_000_[2]),
    .Q(count[2]),
    .QN(_049_)
  );
  DFF_X1 _106_ (
    .CK(clk),
    .D(_000_[3]),
    .Q(count[3]),
    .QN(_048_)
  );
  DFF_X1 _107_ (
    .CK(clk),
    .D(_000_[4]),
    .Q(count[4]),
    .QN(_047_)
  );
  DFF_X1 _108_ (
    .CK(clk),
    .D(_000_[5]),
    .Q(count[5]),
    .QN(_046_)
  );
  DFF_X1 _109_ (
    .CK(clk),
    .D(_000_[6]),
    .Q(count[6]),
    .QN(_045_)
  );
  DFF_X1 _110_ (
    .CK(clk),
    .D(_000_[7]),
    .Q(count[7]),
    .QN(_044_)
  );
endmodule
