/* Generated by Yosys 0.45+106 (git sha1 982fade0d, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

module serial_adder(a, b, clk, sum, carry);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  input a;
  wire a;
  input b;
  wire b;
  output carry;
  wire carry;
  input clk;
  wire clk;
  wire state;
  output sum;
  wire sum;
  INV _11_ (
    .I(state),
    .ZN(_07_)
  );
  INV _12_ (
    .I(b),
    .ZN(_08_)
  );
  INV _13_ (
    .I(a),
    .ZN(_00_)
  );
  NAND2 _14_ (
    .A1(b),
    .A2(a),
    .ZN(_01_)
  );
  NAND2 _15_ (
    .A1(_08_),
    .A2(_00_),
    .ZN(_02_)
  );
  INV _16_ (
    .I(_02_),
    .ZN(_03_)
  );
  NAND2 _17_ (
    .A1(_07_),
    .A2(_03_),
    .ZN(_04_)
  );
  NAND2 _18_ (
    .A1(_01_),
    .A2(_04_),
    .ZN(_05_)
  );
  INV _19_ (
    .I(_05_),
    .ZN(_10_)
  );
  NAND2 _20_ (
    .A1(state),
    .A2(_02_),
    .ZN(_06_)
  );
  NAND2 _21_ (
    .A1(_01_),
    .A2(_06_),
    .ZN(_09_)
  );
  BUF _22_ (
    .I(state),
    .Z(carry)
  );
  DFFRNQ _23_ (
    .CLK(clk),
    .D(_10_),
    .Q(sum),
    .RN(1'h1)
  );
  DFFRNQ _24_ (
    .CLK(clk),
    .D(_09_),
    .Q(state),
    .RN(1'h1)
  );
endmodule
